- name: Cloud-1 install dependencies
  hosts: myhosts
  become: true
  tasks:
    # install packages to allow apt to use a repository over HTTPS:
    - name: Install docker packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # apt-key fingerprint
    - name: Add Docker s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # apt-key fingerprint
    - name: Verify that we have the key with the fingerprint
      apt_key:
        id: 0EBFCD88
        state: present

    # add-apt-repository
    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
        state: present
        update_cache: yes

    # apt-get update
    - name: Update apt packages
      apt:
        update_cache: yes

    # install docker-ce latetst verion
    - name: Install docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    # enable docker service to start at boot
    - name: Enable docker.service
      systemd:
        name: docker.service
        daemon_reload: true
        enabled: true

    # enable container service to start at boot
    - name: Enable containerd.service
      systemd:
        name: containerd.service
        daemon_reload: true
        enabled: true

    # sudo groupadd docker
    - name: Create "docker" group
      group:
        name: docker
        state: present

    # sudo usermod -aG docker root
    - name: Add remote user to "docker" group
      user:
        name: cloud1-user
        groups:
          - docker
        append: yes

    - name: Reset ssh connection to allow user changes to affect ansible user
      meta: reset_connection

- name: Cloud-1 Deploy
  hosts: myhosts
  collections:
    - community.docker
  tasks:
    - name: copy Inception
      copy:
        src: files/inception
        dest: ~/app/

    - name: copy Dot Env
      copy:
        src: files/.env
        dest: ~/app/inception/.env

    - name: deploy Inception
      community.docker.docker_compose_v2:
        project_src: ~/app/inception
        files:
          - docker-compose.yml
